# Generated by Django 5.2.8 on 2025-11-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=250)),
                ('annee', models.IntegerField()),
                ('duree', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('couverture', models.CharField(max_length=100)),
                ('favoris', models.IntegerField(default=0)),
            ],
        ),
    ]
