# Generated by Django 5.2.8 on 2025-11-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_film_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='couverture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
