# Generated by Django 5.2.8 on 2025-11-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_categorie_titre_alter_film_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='categorie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.categorie'),
            preserve_default=False,
        ),
    ]
