# Generated by Django 5.2.8 on 2025-11-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_categorie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='categorie_id',
            new_name='categorie',
        ),
    ]
